#include <stdio.h>
#include <time.h>
#define KRED "\x1B[31m"
#define KWHT  "\x1B[37m"
#define KBLU  "\x1B[34m"
#define KGRN  "\x1B[32m"

int main ()
{
// integer arrays to hold users numbers
int userNumbers[19], userNumbersCopy[19];
//multi-dimensional array that is user to hold the game board
int gameBoard[8][10];
//int variables to users Input, the 80 numbers for the game board and for the for loops
int i, j, userNumber, gameBoardCounter=1;
//int variable that will be used to store a value form the userNumber array and check if it is 
//greater than 80
int check;


//int arrays that hold the numbers that will be auto generated by the computer
int compNums[19]={0}, compNumsCopy[19];
//int variables used to store auto generated number
int rnd;
//'a' is to compare the computers random numbers and help sort them from least to greatest
int a; 
//'b' 'c' are used as counters for the compNums/userNumbers arrays. used to help change the text color on the game board
int b=0, c=0;


//prompting the user to enter their 20 number. also, program will re-direct here if the user
//enters the same number twoice, selects 0 as a number, and if hey select a number higher than 80
ENTERNUMBERS:printf("Please enter your 20 numbers: ");

//START OF: for loop that stores all of the user inputs into the userNumbers array and the userNumbersCopy array
for(i=0; i<20; i++)
{
	scanf("%d", &userNumber);
	
	userNumbers[i] = userNumber;
	userNumbersCopy[i]=userNumber;
	
}
//END OF: for loop that stores all of the user inputs into the userNumbers array and the userNumbersCopy array

//START OF: for loop that checks for any zeros entered by the user
for(i=0; i< 20; i++)
{
	//if loop detects a zero it will print this error message and redirect the user to re-enter their numbers
	if(userNumbers[i] == 0)
	{
		printf("Zero is not a valid number please pick 20 numbers from 1 to 80 \n");
		goto ENTERNUMBERS;
		break;
	}
	
}
//END OF: for loop that checks for any zeros entered by the user

//START OF: for loop that checks equal numbers (same number entered twice)
for(i=0; i < 20; i++)
{
	for(j=i+1; j<20; j++)
	{
		//if the same number is entered twice an error message will print and redirect the user to re-enter their numbers
		if(userNumbers[i]==userNumbersCopy[j])
		{
			printf("you picked the same number twice! please re-select your numbers and make sure that none of them are the same \n");
			goto ENTERNUMBERS;
		}
		break;
	}
	//break;
}
//START OF: for loop that checks equal numbers (same number entered twice)

//START OF: for loop that checks if the number entered by the user is greater than 80
for(i=0; i< 20; i++)
{
	check = userNumbers[i];
	//if number is greater than 80 the program will print error massage and redirect the user to re-enter their numbers
	if(check > 80)
	{
		printf("invalid number. Please enter a number less than 80 \n");
		goto ENTERNUMBERS;
		break;
	}
	
}
//END OF: for loop that checks if the number entered by the user is greater than 80



printf("Here are the numbers you picked: ");
for(i=0; i<20; i++)
{
	printf("%d ", userNumbers[i]);
}
printf("\n");

//used to get the curent time of the computer and help generate different random numbers
srand(time(NULL));

//START OF: for loop that generates random numbers and stores them in the compNums array and compNumsCopy
for(i=0; i<20; i++)
{
	
	rnd = rand() %81;
	compNums[i]=rnd;
	compNumsCopy[i] = compNums[i];
}
//END OF: for loop that generates random numbers and stores them in the compNums array and compNumsCopy

//START OF: for loop that check and makes sure that the computer does not select the same number twice
for(i=0; i < 20; i++)
{
	for(j=i+1; j<20; j++)
	{
	//if there are equal numbers it will regenerate a new number.
	//goto label is used to re-check if the numbers are equal after the first pass has been completes
       CENTERNUMBERS:if(compNums[i] == compNumsCopy[j])
	             {
			
			rnd = rand()%81;
			compNums[i]=rnd;
			goto CENTERNUMBERS;
		     }	
	 }
}
//END OF: for loop that check and makes sure that the computer does not select the same number twice

//START OF: for loop that will orginize the compNums array from lowest to highest number.
for (i = 0; i < 20; ++i)
    {
        for (j = i + 1; j < 20; ++j)
        {
            if (compNums[i] > compNums[j])
            {
                a = compNums[i];
                compNums[i] = compNums[j];
                compNums[j] = a;
            }
        }
    }
//END OF: for loop that will orginize the compNums array from lowest to highest number

//START OF: for loop that will orginize the userNumbers array from lowest to highest number.
for (i = 0; i < 20; ++i)
    {
        for (j = i + 1; j < 20; ++j)
        {
            if (userNumbers[i] > userNumbers[j])
            {
                a = userNumbers[i];
                userNumbers[i] = userNumbers[j];
                userNumbers[j] = a;
            }
        }
    }
//END OF: for loop that will orginize the userNumbers array from lowest to highest number

//START OF: for loop that will print the computers numbers to the terminal
printf("here are the computers Numbers: ");
for(i=0; i<20; i++)
{
	printf("%d ", compNums[i]);

}
//END OF: for loop that will print the computers numbers to the terminal
printf("\n\n");

//START OF: for loop that will populate the game board array with the numbers 1-80
for(i=0; i<8; i++)
{
	for(j=0; j<10; j++)
	{
		gameBoard[i][j] = gameBoardCounter;
		gameBoardCounter++;
	}
}
//END OF: for loop that will populate the game board array with the numbers 1-80

//START OF: for loop that will print the game board to the terminal, changing the color of the numbers that the computer selected		
for(i=0; i<8; i++)
{
	for(j=0; j<10; j++)
	{
		//if both the users number and computers number are equal to the current number 
		//being printed the text color will change to the color green
   UCRECHECKROW:if(userNumbers[c] == gameBoard[i][j] &&  compNums[b] == gameBoard[i][j])
		{
			printf("%s", KGRN);
			c++;
			b++;
			goto URECHECKROW;
		}
		else
		{
     		    //if the number selected by the computer is equal to the current number being 
		    //printed out on the game board the text color will change to red
    	CRECHECKROW:if(compNums[b] == gameBoard[i][j])
		    {
			printf("%s", KRED);
			b++;
			goto CRECHECKROW;
		    }
		    //if the number selected by the user is equal to the current number being 
		    //printed on the game board the text color will change to the color blue
    	URECHECKROW:if(userNumbers[c] == gameBoard[i][j])
	            {
			printf("%s", KBLU);
			c++;
			goto URECHECKROW;
		    }
		}
		printf("[");
		printf("%2d", gameBoard[i][j]);
		printf("]");
		printf("%s", KWHT);
		
		
	}
	printf("\n");
}
printf("\n");

return 0;
}
